version: '3.3'

networks:
  wordpress_net:
    driver: bridge

volumes: 
    db:

services: 

    wordpress:
        build: .
        ports: 
            - 8080:80
        environment: 
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wpuser
            WORDPRESS_DB_PASSWORD: wppass
            WORDPRESS_DB_NAME: wpdb
        volumes: 
            - ./src:/var/www/html/wp-content/plugins/meu-plugin
        networks: 
            - wordpress_net
    db:
        image: mysql:5.7
        environment: 
            MYSQL_DATABASE: wpdb
            MYSQL_USER: wpuser
            MYSQL_PASSWORD: wppass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes: 
            - db:/var/lib/mysql
        networks: 
            - wordpress_net

    adminer:
        depends_on: 
            - db
        image: adminer
        ports: 
            - 8888:8080
        networks: 
            - wordpress_net
      
